EMAIL_INVALID_CODE = 101
EMAIL_INVALID_STRING = "Email invalid"
PASSWORD_INVALID_CODE = 102
PASSWORD_INVALID_STRING = "Password invalid"

FAILED_TO_COMMIT_USER_CODE = 201
FAILED_TO_COMMIT_USER_STRING = "Failed to commit user to database"
FAILED_TO_QUERY_FOR_USER_CODE = 202
FAILED_TO_QUERY_FOR_USER_STRING = "Failed to query database for user"

USER_WITH_EMAIL_ALREADY_EXISTS_CODE = 301
USER_WITH_EMAIL_ALREADY_EXISTS_STRING = "User with that email already exists"
